ifdef OS
	RM = del /q
	FixPath = $(subst /,\,s1)
	EXEC = exe
else
	ifeq ($(shell uname), Linux)
		RM = rm -rf
		FixPath = s1
		EXEC = out
	endif
endif



build : main.c
	gcc main.c -o multifile.$(EXEC)

run : build
	./multifile.$(EXEC)

